package TraceLinkOntologyDBConnector;

// This class is designed to represent the trace link ontology stored in DB (table tl_class & tl_class_hierarchy)
// Instances of this class is typically generated by TMSDBManager
public class DBOntology {
	
	private TMSDBManager DBManager;	//The TMSDBManager that created the DBOntology

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
